metadata:
  namespace: demo
  labels:
    app: demo
deployment:
  replicaCount: 1
  namespace: demo
  name: demo
container:
  name: demo
  image:
    name: robbyra98/argo-image-updater-poc
    tag: 0.0.0
    pullPolicy: IfNotPresent
  port: 8080
  protocol: TCP
service:
  name: demo
  type: NodePort
  targetPort: 8080

