metadata:
  namespace: demo
  labels:
    app: demo
deployment:
  replicaCount: 1
  namespace: demo
  name: demo
image:
  name: robbyra98/argo-image-updater-poc
  tag: 0.0.4
  pullPolicy: IfNotPresent
container:
  name: demo
  port: 8080
  protocol: TCP
service:
  name: demo
  type: NodePort
  targetPort: 8080

